spring:
  datasource:
    url: jdbc:h2:mem:dev-kidult
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
  h2:
    console:
      enabled: true
  data:
    web:
      pageable:
        default-page-size: 5
        one-indexed-parameters: true

server:
  port: 8081


