drop table if exists `user`;
create table `user`
(
    id     bigint generated by default as identity,
    `name` varchar(100),
    age    int,
    primary key (id)
);

insert into `user` (`name`, age)
values ('김아무개', 22),
       ('김부각', 33),
       ('이승철', 44),
       ('이이', 55),
       ('황무지', 66),
       ('정철', 14),
       ('땡중', 5),
       ('아무개', 40),
       ('팽숙', 11),
       ('정누구', 16),
       ('이산', 29),
       ('최씨', 46),
       ('누구냐넌', 24),
       ('박씨가없네', 45),
       ('최박', 19),
       ('정두팔', 38),
       ('박박', 39),
       ('김이박', 32)
